export { addImageToCurrentSlide } from './addImageToCurrentSlide'
export { addMoveableToElements } from './addMoveableToElements'
export { blobToBase64 } from './blobToBase64'
export { getSlidesHTML } from './getSlidesHTML'
export { loadSlideshow } from './loadSlideshow'
export { parseGoogleSlides } from './parseGoogleSlides'
export { isHTML } from './isHTML'
export { hashCode } from './hashCode'
export * from './downloadSlides'
export { rgbToHex } from './rgbToHex'
