name: push to swarm

on:
  push:
    branches:
      - main
      - development
jobs:
  build-fdp-storage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set vars per branch
        id: vars
        run: |
          if [ "$GITHUB_REF_NAME" == 'main' ]; then
              echo "NEXT_PUBLIC_FAIROSHOST=https://fairos.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_FAIRDRIVEHOST=https://fairdrive.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_BEE_URL=https://bee-1.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_RPC_URL=https://xdai.dev.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_BASE_PATH=/apps/slidezz/" >> "$GITHUB_ENV"
              echo "PURGE_URL=https://fairdrive.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "SWARM_URL=https://gateway.fairdatasociety.org/proxy/" >> "$GITHUB_ENV"
              echo "SIGNER=SIGNER_$GITHUB_REF_NAME" >> "$GITHUB_ENV"
              echo "DEPLOYMENT=." >> "$GITHUB_ENV"
          elif [ "$GITHUB_REF_NAME" == 'development' ]; then
              echo "NEXT_PUBLIC_FAIROSHOST=https://fairos.dev.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_FAIRDRIVEHOST=https://fairdrive.dev.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_BEE_URL=https://bee-1.dev.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "NEXT_PUBLIC_RPC_URL=https://xdai.dev.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "PURGE_URL=https://fairdrive.dev.fairdatasociety.org" >> "$GITHUB_ENV"
              echo "SWARM_URL=https://gateway.dev.fairdatasociety.org/proxy/" >> "$GITHUB_ENV"
              echo "SIGNER=SIGNER_$GITHUB_REF_NAME" >> "$GITHUB_ENV"
              echo "DEPLOYMENT=.dev." >> "$GITHUB_ENV"
           fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Install fdp-storage dependencies
        run: npm install --prefix  node_modules/@fairdatasociety/fdp-storage/

      - name: Build fdp-storage
        run: npm run prepare --prefix node_modules/@fairdatasociety/fdp-storage/

      - name: Copy fdp-storage index
        run: cp node_modules/@fairdatasociety/fdp-storage/dist/index.browser.min.js node_modules/@fairdatasociety/fdp-storage/dist/index.min.js

      - name: Copy fdp-storage index map
        run: cp node_modules/@fairdatasociety/fdp-storage/dist/index.browser.min.js.map node_modules/@fairdatasociety/fdp-storage/dist/index.min.js.map

      - name: copy NEXT vars to .env
        run: |
          env |grep 'NEXT_PUBLIC' > .env

      - name: Build
        run: yarn build:static
        env:
          NEXT_PUBLIC_BASE_PATH: /apps/slidezz
          NEXT_PUBLIC_BATCH_ID: 'b48953f094938e65f64addef4049b1f41b8140f3673053f2bb0db74b0b15f7be'
          NEXT_PUBLIC_FDS_REGISTRAR: '0xF4C9Cd25031E3BB8c5618299bf35b349c1aAb6A9'
          NEXT_PUBLIC_ENS_REGISTRY: '0x42B22483e3c8dF794f351939620572d1a3193c12'
          NEXT_PUBLIC_PUBLIC_RESOLVER: '0xbfeCC6c32B224F7D0026ac86506Fe40A9607BD14'
          NEXT_PUBLIC_SLIDES_POD: fair-slideshows
          NEXT_PUBLIC_IS_STATIC: true

      - name: Upload
        id: swarm-upload
        uses: ethersphere/swarm-actions/upload-dir@latest
        with:
          bee-url: ${{ env.SWARM_URL }}
          dir: ./out
          index-document: index.html
          timeout: 200000

      - name: update feed
        id: swarm-feed
        uses: ethersphere/swarm-actions/write-feed@latest
        with:
          topic: slidezz
          bee-url: ${{ env.SWARM_URL }}
          reference: ${{ steps.swarm-upload.outputs.reference }}
          signer: ${{ secrets[env.SIGNER] }}

      - name: print references
        run: |
          echo "upload ref: " ${{ steps.swarm-upload.outputs.reference }}
          echo "feed ref: " ${{ steps.swarm-feed.outputs.reference }}
          echo "CID: " ${{ steps.swarm-cid.outputs.cid }}
          echo "Feed Manifest: " ${{ steps.swarm-feed.outputs.manifest }}

      - name: purge cache
        env:
          TOKEN: '${{ secrets.purge_token }}'
        run: |
          curl -s ${{ env.PURGE_URL }}/deploy/purge?token=${{ secrets.purge_token }} -H "site: fairdrive${{ env.DEPLOYMENT }}fairdatasociety.org" -H "uri: apps/slidezz/"
